# Site settings
title: Steffen D. Sommer
subtitle: "Swift Developer from Copenhagen, Denmark"
email: steffendsommer@icloud.com
description: "A developer blogging about topics such as Server-Side Swift, Vapor, Functional Reactive Programming, MVVM, Clean Architecture, Dependency Injection, Unit Testing, AutoLayout, Productivity and more."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.steffendsommer.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/
future: true

collections:
  projects:
    output: true
    permalink: /projects/:path/
    layout: project
  talks:
    output: true
    permalink: /talks/:path/
    layout: talk

twitter:
  username: steffendsommer
logo: "assets/logo_full.png"
social:
  name: Steffen D. Sommer
  links:
    - https://twitter.com/steffendsommer
    - https://www.facebook.com/steffendsommer
    - http://instagram.com/steffendsommer/
    - https://www.linkedin.com/in/steffendsommer
    - https://github.com/steffendsommer
    - http://stackoverflow.com/users/4145708/steffen-d-sommer

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Gems
gems:
  - jekyll-sitemap
  - jekyll-seo-tag